Brigades:
-   GuildID: ENC[AES256_GCM,data:qj9yBI0bwvNJVDenjFj/Qast,iv:9PVtQ4vBSm4Lfgnvkr6zMBSjSmNB2Txr8i0xA56wlgs=,tag:m1tZ+8IJwVtVC5ZOZds05w==,type:str]
    ProjectCategoryID: ENC[AES256_GCM,data:HqwsXuRWl/p5VTlzTR2xElGb,iv:V566orpyc1MqgskE5yKFRpigaoSW0FFkGNFlW7seISY=,tag:eAq2+UcWLLNAR86ZanHYhA==,type:str]
    EveryoneRole: ENC[AES256_GCM,data:o1ciEubG1mOUsFK5nv904gJg,iv:AIMdG90Kggx7etvWy9wy9TyxrXqvKTThwDiy3vmscQY=,tag:GDQOwTBFx7oRkPw2bcGAmg==,type:str]
    #ENC[AES256_GCM,data:9ePW149sujIAIITJ2uvPkQ3mf6bMcvAn7SEvOX4ZHbgb8FhSCkP3IP1jTtfk5O8HKu8uz9l/lxK/wFCJlXDfQX/tA1s=,iv:AIFG8FEwGcGS0uq8d2qYXcc/Lms5LFGiO2BUuzS3G9E=,tag:BZLVCJS0jn/kenS/PPamiQ==,type:comment]
    NewRole: ENC[AES256_GCM,data:hlQBqzaI4L8mPNt//fTIL7gp,iv:U5JGWcUhjLMMVFvO9esx+RDh3DJTaXw98Kmm87n+lkM=,tag:IAe2FX7baCFZ9hDPC5UxrQ==,type:str]
    OnboardingRole: ENC[AES256_GCM,data:2mF9gFst2ouTt9NH/Xmk2tuo,iv:xHHwVJCX7t6z6vPoMBnz47d7Neb/QEi9EIO+Y7nQ7dE=,tag:rbcv0ElakHbSRh5799uRGw==,type:str]
    MemberRole: ENC[AES256_GCM,data:0QMzHQuUEMbL3jorxlWNiVps,iv:G3Xw1dQKmxTQziXdIvYC6UxLoiK0IMMHdLSrOL1Bi2I=,tag:bccQ6kAs2bxxiXu2ssBv7w==,type:str]
    OnboardingInviteCode: ENC[AES256_GCM,data:z6bInEapvw==,iv:bHycugOJmUC0wUNLFAuqGv+R+jqZxPzkJFaL+p9X6K0=,tag:VPly0ZrFEMceDszqf/AeeQ==,type:str]
    CodeOfConductMessageID: ENC[AES256_GCM,data:K3UDjApDuHTlupow8ci2J+JP,iv:iuqIFVSuCb0itgDvk0feap3owHLKMNgfCgBacPPZRnk=,tag:kkNIDPP0n4yaGqlBjOVisA==,type:str]
    AgendaFolderID: ENC[AES256_GCM,data:M2uw6toYkWJAMkkp9bF/gFZ/eNlPcwX9S+aZ5Jj5/MTm,iv:tTdB0/bPYXHGR+8aBBStqEKVvy7r3OLid7EYtcfSgxc=,tag:MJEcC4pLYrrA/lwiH17Oug==,type:str]
    LocationString: ENC[AES256_GCM,data:YKzQOTpt0Vk7hoGA97Q=,iv:YPGlGLXDhOWF/uKp/vJ1MmZSvzCTd0qc5TIMRNpT5gA=,tag:7WcMnW77CrIWTX/CXoQgrg==,type:str]
    AirtableBaseID: ENC[AES256_GCM,data:MQO7jYyY/w0hFbFfdYa4HBs=,iv:MdLoh0Suvcxr9Bg767TusA2di+ybbV6XuCulXRDdzyo=,tag:yRDZ+mr82bHzEAp269crEQ==,type:str]
    Files:
        attendance: ENC[AES256_GCM,data:IP4wOsiGX/2ekJgvqKJrpj/Jymyk8yfYip4Y7VIZwe8Spb0CFjPKSumzlgo=,iv:PIoWA4mxuAgS347oTDixR27Ct2q+fc0WmopFOEhKrhU=,tag:XzXvAIoU7LmlfWMX4E7ESg==,type:str]
        onboarding: ENC[AES256_GCM,data:lyR5lqxbIWJptFjzOA40Jj8w5+PwbjUNAEpX45Pag4kmeT1H8x9rlvG4sxQ=,iv:V+rYYJU9gyIU8LdsaJSx1n7u2Fze9bz+NtH/1Sbr0fU=,tag:iC5tvb6X+88/UpZKFiTSaA==,type:str]
    GithubOrg: ENC[AES256_GCM,data:0DkyyJ9CZySFat4/YQ==,iv:tbpyaL5X714SnVk6SjT+AyGsCnvhRiDydQC9vdwHVQM=,tag:n+lSnMzZPexrZC0RyFBjpw==,type:str]
    IssueEmoji: ENC[AES256_GCM,data:HIOal+8Go3gudRxhGg==,iv:yll4QGnpMlpsGJ/I8cfOst33SwuF8vOGq0sC+yrfSyE=,tag:+ctRNBJKK6h0bUJT8R9DEw==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-west-2:556038155243:key/6f2cd560-13c5-4aa7-adc9-a92f0d8a133d
        created_at: '2019-08-06T02:46:17Z'
        enc: AQICAHjmDnK11vv45E39SDTRoYUS9AEedfOhlMMxstVZARgShgFh7PkOByFiwGCCP4x0CyU6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMi0oBK983g3vUiOjFAgEQgDuAQTrT8KJcx+3a7q67FCDMMZcPKCbHm7WStbyK8EZNGwciOtbZeVcNNepGD7dgnKnmI+N3uUbOnmFs7Q==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-08-16T01:11:23Z'
    mac: ENC[AES256_GCM,data:zQTy6EJAfYYDc33yYiglmed+8KsnoiQpDcym05b7k2OaNco0uqx5wOYuXft8uwskV1CV5DTrrfsPzjM3NIqG9mzc4dP6FwqYg+0+lzBRO7ki2NjFT3FVsUDaxd4O3Mo3jOC80T4RmlN1WLOuRZ2QEWcnPKQYEdpO93OGijckWRs=,iv:TIYZE7XLGZ7VDWDp+EiGSbH88vU7OA+WIcQ4KL7sALQ=,tag:cUToM6hyEIm8n5Tt9IU3dw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.3.1
